version: '3'
services:
  app:
    build: .
    volumes:
      - ./laravel:/var/www/html/todo_app
    ports:
      - 8000:8000
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: db-host
    restart: always
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql